# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: input
        id: step_one
        run: |
          line1="line1"
          line2="line2-1
          line2-2"
          echo "line1=$line1" >> $GITHUB_ENV
          echo "line2=$line2" >> $GITHUB_ENV
      - name: output
        run: |
          echo "env.line1=${{ env.line1 }}"
          echo "env.line2=${{ env.line2 }}"
